import shutil
import logging
import platform
from logging import Filter
from datetime import datetime
from pathlib import Path

from .settings import Settings

logger = logging.getLogger(__name__)

LOG_PATH = Path("experiment.log")


class LogFilter(Filter):
    """
    Logging filter that allows all log records generated by user code
    (loggers named '__main__' or starting with 'src.').
    """

    def filter(self, record: logging.LogRecord) -> bool:
        """
        Determine if a log record should be emitted based on its logger name.
        
        Parameters
        ----------
        record : logging.LogRecord
            The log record to evaluate.
        
        Returns
        -------
        bool
            True if the record should be emitted, False otherwise.
        """
        logger_name = record.name
        return logger_name == "__main__" or logger_name.startswith("src.")


class LogSetup:
    """
    Encapsulates logging configuration and management.

    Parameters
    ----------
    settings : Settings
        The unified settings object containing logging configuration and output directory.
    """

    def __init__(self, settings: "Settings") -> None:
        self.log_level = settings.logging.log_level
        self.output_dir = settings.data.create_output_dir()
        self.config_params_path = settings.data.config_params_path

    @staticmethod
    def setup_bootstrap_logging() -> None:
        """Configure minimal console logging for application startup."""
        console_handler = logging.StreamHandler()
        console_handler.setLevel(logging.INFO)
        console_handler.addFilter(LogFilter())

        formatter = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
        console_handler.setFormatter(formatter)

        logging.basicConfig(
            level=logging.INFO,
            handlers=[console_handler],
            force=True,
        )

    def setup_logging(self) -> None:
        """Configure full logging with file and console handlers."""
        file_handler = logging.FileHandler(str(LOG_PATH), mode="a")
        file_handler.setLevel(logging.WARNING)

        console_handler = logging.StreamHandler()
        console_handler.setLevel(self.log_level)
        console_handler.addFilter(LogFilter())

        formatter = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
        file_handler.setFormatter(formatter)
        console_handler.setFormatter(formatter)

        logging.basicConfig(
            level=logging.DEBUG,
            handlers=[file_handler, console_handler],
            force=True,
        )

        logging.captureWarnings(True)

    def write_log_metadata(self) -> None:
        """Write experiment metadata to the log file at the start of a run."""
        metadata = [
            "========== New Experiment ==========",
            f"Timestamp       : {datetime.now().isoformat()}",
            f"Output Directory: {self.output_dir}",
            f"Platform        : {platform.system()} {platform.release()}",
            f"Python Version  : {platform.python_version()}",
        ]

        env_path = Path(".env")
        if env_path.exists():
            metadata.append("\n# .env contents:")
            with open(env_path, "r") as f:
                metadata.extend(["  " + line.strip() for line in f if line.strip()])

        if self.config_params_path.exists():
            metadata.append("\n# config_params.json contents:")
            with open(self.config_params_path, "r") as f:
                metadata.extend(["  " + line.rstrip() for line in f])

        metadata.append("")
        with open(LOG_PATH, "a") as f:
            f.write("\n".join(metadata) + "\n")

    def cleanup(self) -> None:
        """Close log handlers and move log file to output directory if possible."""
        if self.output_dir and LOG_PATH.exists():
            try:
                root_logger = logging.getLogger()
                for handler in root_logger.handlers[:]:
                    if isinstance(handler, logging.FileHandler):
                        handler.close()
                        root_logger.removeHandler(handler)

                shutil.move(str(LOG_PATH), str(Path(self.output_dir) / LOG_PATH.name))
            except Exception as e:
                logger.warning(f"Could not move log file to output directory: {e}")
